# Generated by Django 6.0.5 on 2026-05-26 11:17

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume in PDF format (Max 2MB).', null=True, upload_to='resumes/', validators=[jobs.models.validate_pdf_file]),
        ),
    ]
