# Generated by Django 6.0.5 on 2026-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_application_resume_url_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_judgment',
            field=models.TextField(blank=True, help_text='2-line professional evaluation summary from Gemini.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.IntegerField(default=0, help_text='Matching score out of 100 calculated by Gemini LLM.'),
        ),
    ]
