# Generated by Django 6.0.5 on 2026-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_ai_judgment_application_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_letter',
            field=models.FileField(blank=True, help_text='Automatically generated PDF offer letter for selected candidates.', null=True, upload_to='offer_letters/'),
        ),
    ]
